# Generated by Django 4.0.4 on 2022-05-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date_of_travel',
            field=models.DateField(),
        ),
    ]
